### ISSUE TITLE
Flops

### ISSUE THREAD

**Issue by guo794** [icandle/CAMixerSR#11]
Why is it that the model I got after changing [1,3,32,32] to [1,3,320,180] on the original code is much more computationally intensive than in the paper?
![computation](https://github.com/icandle/CAMixerSR/assets/132817905/d0760188-1c13-4b48-8701-e4c77ca41267)

**Comment by icandle** [comment]
For Large-Image SR, the FLOPs are calculated as ClassSR. For lightweight SR,  we use fvcore to directly compute the MAdds with

```
from fvcore.nn import FlopCountAnalysis, flop_count_table
```
