### ISSUE TITLE
核心work的模块是啥

### ISSUE THREAD

**Issue by rubbish001** [icandle/CAMixerSR#12]
请问一下，您这个工程中最主要能work的模块是啥，我这里的需要可能跟你不一样，你的是能分出空白的和需要注意力的区域，我这里区分不出来，在空白的区域可能也需要恢复出东西来，怎么解决呢，有推荐地论文吗

**Comment by rubbish001** [comment]
不要mask 效果如何？

**Comment by icandle** [comment]
主要work的是CAMixer，但基本上来说，这篇工作依赖于对于复杂和简单区域采用不同复杂的的计算获得性能改善。如果区域分别不出来的话，可能需要其他指标。因为CAMixer是用图像区域的复杂度进行分类，这个指标也可以换成其他的。如果不要mask那就是相当于一个普通的WSA和卷积的结合，效果类似但计算量比较大。

**Comment by ButoneDream** [comment]
您好 请问如何获得图像区域的复杂度，具体指标是？

**Comment by rubbish001** [comment]
没有获取，直接全部弄进去搞

**Comment by ButoneDream** [comment]
直接predictor 分类得到 二进制 mask ？

**Comment by icandle** [comment]
是的，这篇工作和classSR一样是用predictor生成mask，但也有用edge score分类的。

**Comment by xsqhust** [comment]
> 是的，这篇工作和classSR一样是用predictor生成mask，但也有用edge score分类的。

你好，请问根据edge score分类的，具体有哪些论文呢，可不可以说一下？谢谢！

**Comment by icandle** [comment]
[Arm: Any-time super-resolution method](https://link.springer.com/chapter/10.1007/978-3-031-19800-7_15)

**Comment by xsqhust** [comment]
> [Arm: Any-time super-resolution method](https://link.springer.com/chapter/10.1007/978-3-031-19800-7_15)
谢谢

**Comment by zhousai-zs** [comment]
> 主要work的是CAMixer，但基本上来说，这篇工作依赖于对于复杂和简单区域采用不同复杂的的计算获得性能改善。如果区域分别不出来的话，可能需要其他指标。因为CAMixer是用图像区域的复杂度进行分类，这个指标也可以换成其他的。如果不要mask那就是相当于一个普通的WSA和卷积的结合，效果类似但计算量比较大。

我试图复现文章中的mask的作用，文章中图4展现了一些图像不同复杂度对应的概率，但是在复现过程中我发现可视化出的mask十分随机，并不能表现出图像的复杂程度，mask的上一步的pred_score也没有我想要的表现。我的问题是想知道作者在可视化图4中的概率和mask与图片复杂度对应关系上使用的是哪一部分的值？这个值应该从整个SR模型中的第几个predictor中得到？Looking forward to your reply, thanks.

**Comment by hujb48** [comment]
> > 主要work的是CAMixer，但基本上来说，这篇工作依赖于对于复杂和简单区域采用不同复杂的的计算获得性能改善。如果区域分别不出来的话，可能需要其他指标。因为CAMixer是用图像区域的复杂度进行分类，这个指标也可以换成其他的。如果不要mask那就是相当于一个普通的WSA和卷积的结合，效果类似但计算量比较大。
> 
> 我试图复现文章中的mask的作用，文章中图4展现了一些图像不同复杂度对应的概率，但是在复现过程中我发现可视化出的mask十分随机，并不能表现出图像的复杂程度，mask的上一步的pred_score也没有我想要的表现。我的问题是想知道作者在可视化图4中的概率和mask与图片复杂度对应关系上使用的是哪一部分的值？这个值应该从整个SR模型中的第几个predictor中得到？Looking forward to your reply, thanks.

The same to you. And I wonder know if you train the model as well on other datasets, and how it works

**Comment by zhousai-zs** [comment]
> > > 主要work的是CAMixer，但基本上来说，这篇工作依赖于对于复杂和简单区域采用不同复杂的的计算获得性能改善。如果区域分别不出来的话，可能需要其他指标。因为CAMixer是用图像区域的复杂度进行分类，这个指标也可以换成其他的。如果不要mask那就是相当于一个普通的WSA和卷积的结合，效果类似但计算量比较大。
> > 
> > 
> > 我试图复现文章中的mask的作用，文章中图4展现了一些图像不同复杂度对应的概率，但是在复现过程中我发现可视化出的mask十分随机，并不能表现出图像的复杂程度，mask的上一步的pred_score也没有我想要的表现。我的问题是想知道作者在可视化图4中的概率和mask与图片复杂度对应关系上使用的是哪一部分的值？这个值应该从整个SR模型中的第几个predictor中得到？Looking forward to your reply, thanks.
> 
> The same to you. And I wonder know if you train the model as well on other datasets, and how it works

Sorry, I just follow this Mask, have not trained the model on other datasets. But you can try to change options/tarin/*.xml to adopt other datasets.

**Comment by hujb48** [comment]
> > > > 主要work的是CAMixer，但基本上来说，这篇工作依赖于对于复杂和简单区域采用不同复杂的的计算获得性能改善。如果区域分别不出来的话，可能需要其他指标。因为CAMixer是用图像区域的复杂度进行分类，这个指标也可以换成其他的。如果不要mask那就是相当于一个普通的WSA和卷积的结合，效果类似但计算量比较大。
> > > 
> > > 
> > > 我试图复现文章中的mask的作用，文章中图4展现了一些图像不同复杂度对应的概率，但是在复现过程中我发现可视化出的mask十分随机，并不能表现出图像的复杂程度，mask的上一步的pred_score也没有我想要的表现。我的问题是想知道作者在可视化图4中的概率和mask与图片复杂度对应关系上使用的是哪一部分的值？这个值应该从整个SR模型中的第几个predictor中得到？Looking forward to your reply, thanks.
> > 
> > 
> > The same to you. And I wonder know if you train the model as well on other datasets, and how it works
> 
> Sorry, I just follow this Mask, have not trained the model on other datasets. But you can try to change options/tarin/*.xml to adopt other datasets.

Thx for your reply!
