### ISSUE TITLE
AssertionError：bird_HR_x4.png is not in lq_paths

### ISSUE THREAD

**Issue by DX3906ghh** [icandle/CAMixerSR#13]
您好，当我执行test_x4.yml文件进行训练时，出现了这样的问题，请问该如何解决呢

![a](https://github.com/icandle/CAMixerSR/assets/157215633/b933b424-6e60-4b7a-a26e-3f541a189c1d)

**Comment by icandle** [comment]
因为BasicSR是通过HR文件夹里的文件来确定文件名的，所以它要求HR和LR文件夹里的文件名相同，有两种处理方式，一种是改写data_util里的path_reader，另一种是用脚本直接把文件名改为相同的。

**Comment by DX3906ghh** [comment]
好的，感谢，我把LR文件夹里的文件名改成跟HR文件一样，确实解决了问题。感谢解惑

**Comment by Jjyykelvin** [comment]
请问遇到这种情况怎么解决？：训练的hq和lq都有800张图，现在会报错0801.png不在lq路径里，然后我就在lq文件夹加了一张，结果又报错hq和lq的图片数量不一样，所以我在hq那边也加了一张，没想到加完又报回第一个错，说0801.png不在lq路径下
