### ISSUE TITLE
AssertionError: 41033_HR_x4.png is not in lq_paths.

### ISSUE THREAD

**Issue by DX3906ghh** [icandle/CAMixerSR#14]
您好，当我运行训练代码时，出现如标题所示的bug。我想请问HR不应该是在HR里吗，为什么要检测这个HR图片不在lq_paths里呢？我该如何解决这个问题呢？谢谢

**Comment by icandle** [comment]
因为BasicSR是通过HR文件夹里的文件来确定文件名的，所以它要求HR和LR文件夹里的文件名相同，有两种处理方式，一种是改写data_util里的path_reader，另一种是用脚本直接把文件名改为相同的。
