### ISSUE TITLE
请问作者有尝试过在这个算法中用GAN吗

### ISSUE THREAD

**Issue by YilanWang** [icandle/CAMixerSR#15]
请问作者,有尝试过对结果再用GAN做些对抗训练吗?就类似REAL-ESRNET & REAL-ESRGAN那样

**Comment by icandle** [comment]
目前还没有，理论上应该是可行的；不过当前的轻量化模型做RealSR的任务可能会效果有限，需要扩大模型尺寸。

**Comment by YilanWang** [comment]
感谢作者的回复~请问如果想在轻量级模型上有一些类似GAN的生成效果要怎么做呢,感觉好像没什么办法 :-)

**Comment by icandle** [comment]
其实想做出类似GAN的生成效果是可以的，只不过没那么惊艳，特别是细节部分差的比较多，但如果做一些简单点的任务轻量化的模型可能会差距小点。
