### ISSUE TITLE
Mask Visualization

### ISSUE THREAD

**Issue by zhousai-zs** [icandle/CAMixerSR#16]
我试图复现文章中的mask的作用，文章中图4展现了一些图像不同复杂度对应的概率，但是在复现过程中我发现可视化出的mask十分随机，并不能表现出图像的复杂程度，mask的上一步的pred_score也没有我想要的表现。我的问题是想知道作者在可视化图4中的概率和mask与图片复杂度对应关系上使用的是哪一部分的值？这个值应该从整个SR模型中的第几个predictor中得到？Looking forward to your reply, thanks.

**Comment by icandle** [comment]
See issue https://github.com/icandle/CAMixerSR/issues/17
