### ISSUE TITLE
"No object named 'CAMixerSR_basicsr' found in 'arch' registry!"

### ISSUE THREAD

**Issue by DD-shine** [icandle/CAMixerSR#23]
您好，我想问一下这个问题怎么解决呢？我看别的博客他们是运行了codes下的setup.py解决的，但是我拉取的代码并没有这个文件。谢谢您 。

**Comment by icandle** [comment]
如果已经pip install basicsr，那么直接进目录就可以运行，如果说你用basicsr的源码的话那么把arch和model里的文件添加到对应的文件夹也可以。

**Comment by icandle** [comment]
> 如果已经pip install basicsr，那么直接进目录就可以运行，如果说你用basicsr的源码的话那么把arch和model里的文件添加到对应的文件夹也可以。

将codes目录中的basicsr更换名称也可以解决
