### ISSUE TITLE
difference of these pretrained models

### ISSUE THREAD

**Issue by HandsLing** [icandle/CAMixerSR#4]
thanks for your share, could you please tell us what the diffrence of these model in pretrained_models folders, thank

**Comment by icandle** [comment]
Thanks for your interest in our work.

For [LargeSR](https://github.com/icandle/CAMixerSR/tree/main/pretrained_models/LargeSR) fold, it contains pre-trained models for large image SR, where CAMixerSR-Base/Medium/Small is with 60/48/32 channels and CAMixerSR-ClassSR means union of both CAMixer and ClassSR strategy. 

For [LightSR](https://github.com/icandle/CAMixerSR/tree/main/pretrained_models/LightSR) fold, the CAMixerSR is Base one with 60 channels and we offer models under varied upscale factors (x2,x3,x4) and training sets (DIV2K, DF2K). 

For [ODISR](https://github.com/icandle/CAMixerSR/tree/main/pretrained_models/ODISR) fold,  pre-trained CAMixerOSRs for ODI-SR are provided with upscale factor x2 and x4.

**Comment by HandsLing** [comment]
thanks a lot
