### ISSUE TITLE
Concerning the addition of three conditions in the article, I have some doubts and don't understand them.

### ISSUE THREAD

**Issue by xuezhongcailian** [icandle/CAMixerSR#5]
![image](https://github.com/icandle/CAMixerSR/assets/31470730/452f6bd9-dd4c-4a6e-8c66-cabef90246aa)
![image](https://github.com/icandle/CAMixerSR/assets/31470730/6f52d2c4-394e-4f99-8098-862c4de9e66d)
Hello, author. Could you please explain why these three conditions are added? Why are they added in this way? Why can we achieve both global and local effects with just a few convolutions?

**Comment by icandle** [comment]
I may not quite understand your concern.  I try to interpret from my view：


- The 'global'  here indicates the same meaning as the 'global' residual. So, the global condition is a relatively coarse condition map (similar to the edge score in ARM), which is shared for all CAMixers. Thus, it can be achieved with few convolutions. 
- The window condition is used to include the relative position, which helps CAMxier know the window/patch. 
- The local condition actually performs more than the former two conditions. Figuratively speaking, the former two conditions (global, local) tell CAMixer the objective situation (e.g. edges, windows), and the latter one (local) leaves the space for customization, which allows CAMixer to determine by actual conditions.

**Comment by xuezhongcailian** [comment]
Thank you for your prompt response. Here, I don't quite understand the concept of "global". What I mean is, why can some convolutional operations achieve global features?

**Comment by icandle** [comment]
I understand. As I mentioned above, the 'global' represents globally-shared instead of feature with global view. This global feature remains the primary or basic information from input images. Thus, two channels are enough for this situation.
