### ISSUE TITLE
How to test with my own local imgs?

### ISSUE THREAD

**Issue by ButoneDream** [icandle/CAMixerSR#6]
when i try to modify the dataset path in the yml file 
i encountered this error :
![image](https://github.com/icandle/CAMixerSR/assets/98502973/3e36c947-2bcb-43a6-ac67-a2e9118c9e99)
could you help me ?

**Comment by ButoneDream** [comment]
sry the paired name is not as the same so the error happend

**Comment by sahleywuyi** [comment]
I also encountered this problem when reproducing the code. May I ask how did you solve this error? thank you !

**Comment by ButoneDream** [comment]
you just need to adjust the image  file name and make sure they are as same in the two dir ( LR  and HR) 
Hope this help for u!

**Comment by sahleywuyi** [comment]
Thank you for your reply. When I used set5 to test, I changed the image names of HR and LR to be the same as them. They can be tested normally, but the test index is very low, PSNR is only 9.7292，Have you ever encountered this problem？  and how should I solve it? thank you very much!
![屏幕截图 2024-04-07 111325](https://github.com/icandle/CAMixerSR/assets/165865256/0fb936a5-c1b1-4985-ac5e-54c0e9c222ff)
![屏幕截图 2024-04-07 111247](https://github.com/icandle/CAMixerSR/assets/165865256/4b34608d-795e-4a3f-a886-dbfc86f77f1e)

**Comment by icandle** [comment]
You can check if the pre-trained model was properly loaded. The _pretrain_network_g: ~ #path to models_ in .yml should be replaced with your local path.
