### ISSUE TITLE
How do I go through the training process?

### ISSUE THREAD

**Issue by dafhafhajfajfna** [icandle/CAMixerSR#7]
How do I go through the training process?

**Comment by icandle** [comment]
We will replenish the readme in a few weeks. For training, you can follow the [basicSR](https://github.com/XPixelGroup/BasicSR/blob/master/docs/TrainTest.md) and use the [CAModel](https://github.com/icandle/CAMixerSR/blob/main/codes/basicsr/models/CAMixerSR_model.py) to replace SRModel in [train_example.yml](https://github.com/icandle/CAMixerSR/blob/main/codes/options/train/train_example.yml).
