### ISSUE TITLE
How can I use pretrained models?

### ISSUE THREAD

**Issue by LiManyuan663** [icandle/CAMixerSR#8]
Excuse me, I wonder how can I use .pth files in the folder 'pretrained models', and how can I use your model to generate a high-resolution picture?

**Comment by icandle** [comment]
For a fast start, you can refer to our [colab implementation](https://colab.research.google.com/gist/icandle/404a89adbc264294dd77edacfd80f3b2/camixersr.ipynb). For test with datasets, you can follow our [How to Test](https://github.com/icandle/CAMixerSR?tab=readme-ov-file#%EF%B8%8F-how-to-test).

**Comment by LiManyuan663** [comment]
thanks！Is this an end to end model? I am confused that when the classify process happens...

**Comment by icandle** [comment]
Yes, it's an end to end model

**Comment by LiManyuan663** [comment]
OKOK。Thanks for your outstanding works！
